<a href="https://colab.research.google.com/github/ammarwesal/pytorch/blob/main/pytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://youtu.be/DbeIqrwb_dE?si=moTxkq7c36w227iN

In [ ]:
import torch

In [ ]:
x=torch.rand(3, requires_grad=True)
print(x)
y=x+2
print(y)
z=y*y*2
print(z)
#z=z.mean()
print(z)#dz/dx

v=torch.tensor([.1,1.0,0.001], dtype=torch.float32)
z.backward(v)#dz/dy
#print(x.grad)


tensor([0.9000, 0.7657, 0.9074], requires_grad=True)
tensor([2.9000, 2.7657, 2.9074], grad_fn=<AddBackward0>)
tensor([16.8202, 15.2982, 16.9061], grad_fn=<MulBackward0>)
tensor([16.8202, 15.2982, 16.9061], grad_fn=<MulBackward0>)


In [ ]:
x=torch.rand(3, requires_grad=True)
print(x)

#3 way to remove gradeing
#x.requires_grad_(False)
#x.detach()
#with torch.no_grad():

x.requires_grad_(False)
print(x)

x.detach()
print(x)

with torch.no_grad():
    y=x+2
    print(y)



tensor([0.8984, 0.3447, 0.9397], requires_grad=True)
tensor([0.8984, 0.3447, 0.9397])
tensor([0.8984, 0.3447, 0.9397])
tensor([2.8984, 2.3447, 2.9397])


In [ ]:
weights=torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output=(weights*3).sum()

    model_output.backward()

    print(weights.grad)

  #while traing giveing wrong results after backpropagation

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [ ]:
weights=torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output=(weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()#solution

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights=torch.ones(4, requires_grad=True)

optimizer=torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor