<a href="https://colab.research.google.com/github/ammarwesal/pytorch/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://youtu.be/exaWOE8jvy8?si=K4u0Gh_BPL-faC4o

In [ ]:
import torch
print(torch.__version__)


2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
    print("CUDA is available")
    print(f"useing GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available")

CUDA is available
useing GPU: Tesla T4


In [ ]:
x=torch.empty(2,2,3)
print(x)

tensor([[[2.8026e-45, 1.8217e-44, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[1.4013e-43, 0.0000e+00, 1.4013e-45],
         [1.4013e-45, 1.9618e-44, 2.1019e-44]]])


In [ ]:
y=torch.zeros(2,2,dtype=torch.double)
print(y.dtype)
print(y.size())

torch.float64
torch.Size([2, 2])


In [ ]:
y=torch.tensor([2.5,0.2])
print(y)

tensor([2.5000, 0.2000])


In [ ]:
y=torch.rand(2,2)
x=torch.rand(2,2)
print(y)
print(x)
#z=x+y
z=torch.add(x,y)
print(z)# similaerly for sub/mul/div

tensor([[0.0536, 0.9526],
        [0.7347, 0.1523]])
tensor([[0.9772, 0.4263],
        [0.3748, 0.5817]])
tensor([[1.0308, 1.3790],
        [1.1095, 0.7340]])


In [ ]:
y=torch.rand(2,2)
x=torch.rand(2,2)
y.add_(x)# similaerly for sub/mul/div
print(y)

tensor([[1.0339, 1.5898],
        [1.4193, 1.7510]])


In [ ]:
x=torch.rand(5,3)
print(x)
print(x[:, 0])
print(x[1, :])
print(x[1, 1].item())

tensor([[0.8414, 0.6628, 0.2680],
        [0.6466, 0.8081, 0.4533],
        [0.4390, 0.9847, 0.0482],
        [0.8145, 0.5951, 0.5881],
        [0.2139, 0.8975, 0.4977]])
tensor([0.8414, 0.6466, 0.4390, 0.8145, 0.2139])
tensor([0.6466, 0.8081, 0.4533])
0.8080822229385376


In [ ]:
x=torch.rand(4,4)
print(x)
y=x.view(16)
print(y)
y=x.view(-1, 8)
print(y)

tensor([[0.4879, 0.1752, 0.2913, 0.0370],
        [0.2917, 0.0326, 0.0200, 0.1829],
        [0.0434, 0.9675, 0.2074, 0.8375],
        [0.0083, 0.9602, 0.8435, 0.2532]])
tensor([0.4879, 0.1752, 0.2913, 0.0370, 0.2917, 0.0326, 0.0200, 0.1829, 0.0434,
        0.9675, 0.2074, 0.8375, 0.0083, 0.9602, 0.8435, 0.2532])
tensor([[0.4879, 0.1752, 0.2913, 0.0370, 0.2917, 0.0326, 0.0200, 0.1829],
        [0.0434, 0.9675, 0.2074, 0.8375, 0.0083, 0.9602, 0.8435, 0.2532]])


In [ ]:
import numpy as np

In [ ]:
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)
print(type(b))

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)

a+=1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
